#!/bin/sh
#
# Automatically adds branch name and branch description to every commit message. 
#

#Check for Valid branch name
NAME=$(git branch | grep '*' | sed 's/* //') 
if [ $NAME == *"HATCH-2"* ]; then
    echo "Warning.$NAME It is best practise to use Jira ID for branch name " >&2    
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi

#Add valid branch name to commit message

DESCRIPTION=$(git config branch."$NAME".description)
TEXT=$(cat "$1" | sed '/^#.*/d')

if [ -n "$TEXT" ]
then
    echo "$NAME"': '$(cat "$1" | sed '/^#.*/d') > "$1"
    if [ -n "$DESCRIPTION" ] 
    then
       echo "" >> "$1"
       echo $DESCRIPTION >> "$1"
    fi
else
    echo "Aborting commit due to empty commit message."
    exit 1
fi