#!/bin/sh
# .git/hooks/post-checkout
# Writes the Jira Id + Jira summary from the recently checked out branch name to the git commit template.
#########################################################################################################

printf "`git rev-parse --abbrev-ref HEAD | grep -o 'HATCH-[0-9]*' | sed 's/* //'`" > .git/.gitmessage.txt