#!/bin/sh
# .git/hooks/post-commit
# re-use last commit message
#########################################################

NAME=$(git rev-parse --abbrev-ref HEAD | grep -o 'HATCH-[0-9]*' | sed 's/* //') 
DESCRIPTION=$(git config branch."$NAME".description)
TEXT=$(cat "$1" | sed '/^#.*/d')

if [ -n "$TEXT" ]
then
    echo "$NAME"': '$(cat "$1" | sed '/^#.*/d') > .git/.gitmessage.txt
fi

printf `git log -1 --pretty=$NAME:%s` > .git/.gitmessage.txt