#!/bin/sh
# .git/hooks/post-commit
# re-use last commit message
#########################################################

NAME=$(git branch | grep '*/^#.*/d' | sed 's/* //') 
DESCRIPTION=$(git config branch."$NAME".description)
TEXT=$(cat "$1" | sed '/^#.*/d')

if [ -n "$TEXT" ]
then
    echo "$NAME"': '$(cat "$1" | sed '/^#.*/d') > .git/.gitmessage.txt
fi

printf $NAME > .git/.gitmessage.txt