#!/bin/sh
# .git/hooks/post-commit
# re-use last commit message
#########################################################

NAME=$(git rev-parse --abbrev-ref HEAD | grep -o 'HATCH-[0-9]*' | sed 's/* //') 
DESCRIPTION=$(git log -1)
TEXT=$(cat "$1" | sed '/^#.*/d')

echo $DESCRIPTION

if [ -n "$TEXT" ]
then
    # echo "$NAME"': '$(cat "$1" | sed '/^#.*/d') > .git/.gitmessage.txt
    echo ""
fi

printf "$NAME $DESCRIPTION --pretty=%s %s "> .git/.gitmessage.txt